service: culqui-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  api:
    handler: dist/handlers/cardController.saveCard
    events:
      - httpApi:
          path: /cardController/saveCard
          method: post

plugins:
  - serverless-offline
